include:
   - memcached.yaml
   - nginx.yaml

services:

  app:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - "memcached"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
