name: Tests

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          docker compose up -d memcached
          pip install -r requirements.txt
          pytest ./tests
          docker compose down memcached
